version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    command:
      - /usr/local/bin/etcd
      - --name
      - etcd
      - --initial-advertise-peer-urls
      - http://etcd:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://etcd:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - etcd=http://etcd:2380
    networks:
      vpcbr:
        ipv4_address: 10.2.50.2
  coredns:
    build: coredns
    networks:
      vpcbr:
        ipv4_address: 10.2.50.3
  prometheus:
    build: prometheus
    dns: 10.2.50.3
    networks:
      vpcbr:
        ipv4_address: 10.2.50.4
  test:
    build: test
    networks:
      vpcbr:
        ipv4_address: 10.2.50.5
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.2.50.0/24